# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feishu_im.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'feishu_im.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65ishu_im.proto\"[\n\x12GetMessagesRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0e\n\x06\x63ursor\x18\x03 \x01(\t\x12\x15\n\x05scene\x18\x04 \x01(\x0e\x32\x06.Scene\"=\n\x06Sender\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\navatar_url\x18\x03 \x01(\t\"\x1b\n\x0bTextContent\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x8d\x01\n\x07Message\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\t\x12\x17\n\x06sender\x18\x03 \x01(\x0b\x32\x07.Sender\x12\x13\n\x0b\x63reate_time\x18\x04 \x01(\x03\x12$\n\x0ctext_content\x18\x05 \x01(\x0b\x32\x0c.TextContentH\x00\x42\t\n\x07\x63ontent\"U\n\x13GetMessagesResponse\x12\x17\n\x05items\x18\x01 \x03(\x0b\x32\x08.Message\x12\x10\n\x08has_more\x18\x02 \x01(\x08\x12\x13\n\x0bnext_cursor\x18\x03 \x01(\t\"0\n\x0eStreamResponse\x12\x1e\n\x0cnew_messages\x18\x01 \x03(\x0b\x32\x08.Message\">\n\nBizRequest\x12\x0f\n\x07service\x18\x01 \x01(\x05\x12\x0e\n\x06method\x18\x02 \x01(\x05\x12\x0f\n\x07payload\x18\x0f \x01(\x0c\"=\n\x0b\x42izResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x0f \x01(\x0c*$\n\x05Scene\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nSCENE_CHAT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feishu_im_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE']._serialized_start=612
  _globals['_SCENE']._serialized_end=648
  _globals['_GETMESSAGESREQUEST']._serialized_start=19
  _globals['_GETMESSAGESREQUEST']._serialized_end=110
  _globals['_SENDER']._serialized_start=112
  _globals['_SENDER']._serialized_end=173
  _globals['_TEXTCONTENT']._serialized_start=175
  _globals['_TEXTCONTENT']._serialized_end=202
  _globals['_MESSAGE']._serialized_start=205
  _globals['_MESSAGE']._serialized_end=346
  _globals['_GETMESSAGESRESPONSE']._serialized_start=348
  _globals['_GETMESSAGESRESPONSE']._serialized_end=433
  _globals['_STREAMRESPONSE']._serialized_start=435
  _globals['_STREAMRESPONSE']._serialized_end=483
  _globals['_BIZREQUEST']._serialized_start=485
  _globals['_BIZREQUEST']._serialized_end=547
  _globals['_BIZRESPONSE']._serialized_start=549
  _globals['_BIZRESPONSE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
